---
title: "Tarea_final"
author: "Graciela Perez"
format: pdf
editor: visual
lang: es
---

# Informe prueba

Texto para evaluacion del curso practicando el uso de quarto y github

```{r}
#| echo: false 
#| warning: false

library(tidyverse)
library(tidymodels)
library(psych)
library(caret)
library(readr)
library(readxl)
library(kableExtra)
library(car)
library(dplyr)
```

You can add options to executable code like this

```{r}
#| echo: false 

ruta_csv <-"C:\\Users\\graciela.perez.IFOP\\Desktop\\quarto_ifop\\winequality-red.csv"
```

Analisis de base de datos de la acidez del vino tinto

```{r}
#| echo: false 
ruta_red <- read.csv("winequality-red.csv")

ruta_red %>% head() %>% kable()%>% kable_classic_2(full_width=F)
```

Re-Escalado

```{r}

#| echo: false 

ruta_red_a =scale(ruta_red, center=T, scale = T) %>% as.data.frame()

ruta_red_a %>% head() %>% kable() %>% kable_classic_2(full_width=F)
```

Tabla 1: composicion quimica del vino

```{r}
#| echo: false 
train=createDataPartition(ruta_red_a$pH, p=0.8, list = FALSE)

train.data=ruta_red_a[train,]
test.data=ruta_red_a[-train,]

```

Modelo 1

```{r}
#| echo: false 

lm1=lm(pH~.-quality,
       train.data)

vif(lm1)
```

Modelo 2

```{r}

#| echo: false 
lm2=update(lm1,.~.-density)

AIC(lm1, lm2)
```

```{r}
#| echo: false 
par(mfrow=c(2,2))

plot(lm1, add.smooth = F)
```
